name: Sync Fork

on:
  schedule:
    - cron: '5 4 * * 5' # At 04:05 on Friday.
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: l3uddz
          base: master
          head: master
          auto_approve: true
          auto_merge: true
