name: Sync Fork

on:
  schedule:
    - cron: '5 4 * * 5' # At 04:05 on Friday.
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: l3uddz
          base: master
          head: master